[noi-bo]
exten => 1001,1,Dial(PJSIP/1001,20)
exten => 1002,1,Dial(PJSIP/1002,20)

exten => 200,1,Answer()
 same => n,Echo()
 same => n,Hangup()

exten => 600,1,Answer()
 same => n,AudioSocket(40325ec2-5efd-4bd3-805f-53576e581d13,127.0.0.1:9092)
 same => n,Hangup()

exten => 900,1,Dial(PJSIP/1002,30)
 same => n,Hangup()